name: Testing Issue creation with workflow actions
on: [push]

jobs:
  create_issue:
    name: Create on push sync issue
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Create on push sync issue
        run: |
          if [[ $CLOSE_PREVIOUS == true ]]; then
            previous_issue_number=$(gh issue list \
              --label "$LABELS" \
              --json number \
              --jq '.[0].number')
            if [[ -n $previous_issue_number ]]; then
              gh issue close "$previous_issue_number"
              gh issue unpin "$previous_issue_number"
            fi
          fi
          new_issue_url=$(gh issue create \
            --title "$TITLE" \
            --label "$LABELS" \
            --project "@kjswartz's kanban test project" \
            --body "$BODY")
          if [[ $PINNED == true ]]; then
            gh issue pin "$new_issue_url"
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          TITLE: New Issue test
          LABELS: documentation,help wanted
          BODY: |
            ## TODO: Add JOb title

            ### 📕 Job Details

            **Proposed Job Title:** _TODO_
            **Proposed Level:** _TODO_
            **Hiring Manager:** _TODO_
            **Skip:** _TODO_
            **VP:** _TODO_
            **Team/Product:** _TODO_
            **Org / Cost Center:**  _TODO_

            ### 🔗 Job Description + Internal Summary

            For the full JD, see the external job post: here (should link)

            Here should be a 1-2 paragraph internal job summary that is meaningful to an engineering Hubber.
          PINNED: false
          CLOSE_PREVIOUS: false
